### ISSUE TITLE
Elírások Telekom EA

### ISSUE THREAD

**Issue by bgabor99** [admarton/ELTE-IK-Jegyzetek#2]
EA 2021.09.08:
Eternet -> Ethernet
Modil -> Mobil
terhelésfelmérés -> Terhelésfelmérés
igényszerinti -> igény szerinti

EA 2021.09.15:
valósidejüség -> valósidejűség
CLIK -> QUIC
cmzés -> címzés
rendszereke -> rendszerek
Encódolás -> hunglish :)
eternet -> Ethernet
Tartalmi: vannak Layer3 switchek tényleg, de a sima switchek Layer2 eszközök.
Tartalmi: "A réteget csak akkor kell implementálni, ha nem kell" ?

EA 3 2021.09.22:
Furier -> Fourier
aproximált -> approximált

EA 4 2021.09.29:
multipexer -> multiplexer
báris -> bázis
csip -> chip
Feleadata -> Feladata
kor -> akkor

EA 5 2021.10.06:
harveresen -> hardveresen
minnnél -> minél
teknika -> technika

EA 6 2021.10.13:
perzisztesn -> perzisztens

EA 7 2021.10.20:
lanokat -> LAN-okat (esetleg)

EA 8 2021.11.03:
nemi -> neki

EA 9 2021.11.17:
hierarhia -> hierarchia
Tartalmi: A osztályú IPv4 címeknál host 2^24 db lehet

EA 10 2021.11.24:
BGT -> BGP ?
hírdetések -> hirdetések
potató -> potato
kölső -> külső

EA 11 2021.12.01:
mezőse -> mezője
Tartalmi: < src_ip, src_port, dest_ip, dest_port > -> < src_ip, src_port, dest_ip, dest_port, proto > //proto=protocol
fi?e_tuple --> five_tuple
QUICK -> QUIC
rendszernet -> rendszert?
köznyékén -> környékén

EA 13 2021.12.08:
Aggregaror -> Aggregátor?
alnevek -> álnevek

**Comment by admarton** [comment]
Remélem kijavítottam mindent.

Tartalmi: "A réteget csak akkor kell implementálni, ha nem kell" ?
- Itt nem tudom, hogy mit akartam írni. Tippeket várok szeretettel.

alnevek -> álnevek
- Itt tényleg alnevekre gondoltam. De meg lehetne fogalmazni jobban is.
- Alnevek alatt a belső routing-ra gondoltam
- pl.: github.com-ot a dns adja de /admarton/ELTE-IK-Jegyzetek már két "alnév" amit már nem a DNS szolgáltató ad.
- Hogyan lehetne ezt jobban megfogalmazni?

**Comment by admarton** [comment]
Megnéztem az utolsó órát is. Azt is megnézheted ha gondolod.

**Comment by bgabor99** [comment]
Előzőekre válaszolva:
Nem tudok arra a mondatra tippet adni én sem :D 
"alnév" jó, már fáradt voltam és környezetbe nem helyeztem a  szót.

Ezeket találtam az utolsó órában:
egyel -> eggyel
propagonation -> propagation

**Comment by admarton** [comment]
Javítottam ezeket.

**Comment by admarton** [comment]
Javítottam ezeket.
