### ISSUE TITLE
MI EA elírások

### ISSUE THREAD

**Issue by bgabor99** [admarton/ELTE-IK-Jegyzetek#3]
Ezeket találtam:

- teknika [többször]
- Műveltek
- mártix
- azstalon
- műveltek
- tezdetben
- "négyzet" felsorolásjel, utána semmi szöveg [Konzi 4 feletti sorban]
- ó  [magában csak ez?, VL-nél]
- "nem általában optimálisabb kihagyni" [nem értettem ezt a mondatot]
- belselyében
- minnél [többször]
- addot

**Comment by admarton** [comment]
Ezt nem találom:
- ó [magában csak ez?, VL-nél]

**Comment by bgabor99** [comment]
"megoldás ó"-ra ha keresel, arra értem hogy ott az 'ó' micsoda

**Comment by bgabor99** [comment]
- aza
