### ISSUE TITLE
AB2 EA Elírások

### ISSUE THREAD

**Issue by bgabor99** [admarton/ELTE-IK-Jegyzetek#5]
- Atomiciti
- Consistenci
- Egyszerő SQL bekezdésben -> Átnevezés alatt "üres" felsorolásjel
- Fizikai tervek készítése alatt "üres" felsorolásjel
- gyorsítható idexel [indexxel/indexekkel]
- klassic ?
- speckó infókat amivel, [vessző amivel elé inkább]
- konjungciós
- öSSZEFOGALÁS
- Kommutatív asszociatív [vessző közéjük]
- Undo log .. Redo logging .. Undo/Redo log [logging helyett akkor Redo-nal is lehetne sima log]
- Legszigorúgg
- Ütememző
- Kis elemeke
- sok trez [tranz?]
- tanz.
- row excludeive [exclusive?]

**Comment by admarton** [comment]
Javítottam
